/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_darren_day15_Simple1 */

#ifndef _Included_com_darren_day15_Simple1
#define _Included_com_darren_day15_Simple1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darren_day15_Simple1
 * Method:    sort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_darren_day15_Simple1_sort
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
