/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_darren_ndk_day13_Simple1 */

#ifndef _Included_com_darren_ndk_day13_Simple1
#define _Included_com_darren_ndk_day13_Simple1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darren_ndk_day13_Simple1
 * Method:    callStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_darren_ndk_day13_Simple1_callStaticMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
