/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_darren_day15_Simple1 */

#ifndef _Included_com_darren_day15_Simple1
#define _Included_com_darren_day15_Simple1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darren_day15_Simple1
 * Method:    sort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_darren_day15_Simple1_sort
  (JNIEnv *, jclass, jintArray);

JNIEXPORT void JNICALL Java_com_darren_day15_Simple1_localRef
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_darren_day15_Simple1_saveGlobalRef
(JNIEnv *, jclass,jstring);

JNIEXPORT jstring JNICALL Java_com_darren_day15_Simple1_getGlobalRef
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_darren_day15_Simple1_delteGlobalRef
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_darren_day15_Simple1_staticLocalCache
(JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_darren_day15_Simple1_initStaticCache
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_darren_day15_Simple1_exception
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
