/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_darren_ndk12_NdkSimple2 */

#ifndef _Included_com_darren_ndk12_NdkSimple2
#define _Included_com_darren_ndk12_NdkSimple2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darren_ndk12_NdkSimple2
 * Method:    getkeepon
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_darren_ndk12_NdkSimple2_getkeepon
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
